apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-react-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: first-react-app
  template:
    metadata:
      labels:
        app: first-react-app
    spec:
      containers:
      - image: thotamanikanta23/my-node-app:0bd0c85427626450e785e71d1b3f63927fdaf2af
        name: first-react-app
        ports:
        - containerPort: 80
